src/Entity/Device.php
<?php

namespace App\Entity;

use App\Repository\DeviceRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DeviceRepository::class)]
class Device
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $name = null;

    #[ORM\Column(length: 30)]
    private ?string $type = null;

    #[ORM\Column(length: 20)]
    private ?string $os = null;

    #[ORM\Column(length: 30)]
    private ?string $os_type = null;

    #[ORM\Column(length: 80)]
    private ?string $model = null;

    #[ORM\Column(length: 100)]
    private ?string $manufacturer = null;

    #[ORM\Column(length: 15)]
    private ?string $ip_address = null;

    #[ORM\Column(length: 80)]
    private ?string $location = null;

    #[ORM\OneToOne(mappedBy: 'device', targetEntity: Specification::class)]
    private ?Specification $specification;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Worker $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getOs(): ?string
    {
        return $this->os;
    }

    public function setOs(string $os): self
    {
        $this->os = $os;

        return $this;
    }

    public function getOsType(): ?string
    {
        return $this->os_type;
    }

    public function setOsType(string $os_type): self
    {
        $this->os_type = $os_type;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getManufacturer(): ?string
    {
        return $this->manufacturer;
    }

    public function setManufacturer(string $manufacturer): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }

    public function getIpAddress(): ?string
    {
        return $this->ip_address;
    }

    public function setIpAddress(string $ip_address): self
    {
        $this->ip_address = $ip_address;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function getUser(): ?Worker
    {
        return $this->user;
    }

    public function setUser(?Worker $worker): self
    {
        $this->user = $worker;

        return $this;
    }

    /**
     * @return Specification|null
     */
    public function getSpecification(): ?Specification
    {
        return $this->specification;
    }


}

src/Form/DeviceType.php
<?php

namespace App\Form;

use App\Entity\Device;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DeviceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('type')
            ->add('os')
            ->add('os_type')
            ->add('model')
            ->add('manufacturer')
            ->add('ip_address')
            ->add('location')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Device::class,
        ]);
    }
}

src/Controller/DeviceController.php
<?php

namespace App\Controller;

use App\Entity\Device;
use App\Form\DeviceType;
use App\Form\DeviceWorkerType;
use App\Repository\CommentRepository;
use App\Repository\DeviceRepository;
use App\Repository\GroupsRepository;
use App\Repository\SpecificationRepository;
use App\Repository\WorkerRepository;
use App\Service\ReportUtil;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/device')]
#[IsGranted("ROLE_USER")]
class DeviceController extends AbstractController
{
    #[Route('/', name: 'app_device_index', methods: ['GET'])]
    public function index(DeviceRepository $deviceRepository, ReportUtil $reportUtil): Response
    {
        $user = $this->getUser();
        if($this->isGranted('ROLE_MANAGER')){
            $admin_group=$user->getAdminGroup();
            $devices = $reportUtil->workerDevices($admin_group);
            return $this->render('device/index.html.twig', [
                'devices' => $devices,
            ]);
        }else{
            return $this->render('device/index.html.twig', [
                'devices' => $deviceRepository->findAll(),
            ]);
        }
    }

    #[Route('/new', name: 'app_device_new', methods: ['GET', 'POST'])]
    #[IsGranted("ROLE_ADMIN")]
    public function new(Request $request, DeviceRepository $deviceRepository): Response
    {
        $device = new Device();
        $form = $this->createForm(DeviceType::class, $device);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $deviceRepository->save($device, true);
            $id=$device->getId();
            $this->addFlash(
                'notice',
                'Device has been created'
            );
            return $this->redirectToRoute('app_specification_new', ['device_id'=>$id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('device/new.html.twig', [
            'device' => $device,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_device_show', methods: ['GET'])]
    public function show(Device $device, SpecificationRepository $specificationRepository, WorkerRepository $workerRepository, CommentRepository $commentRepository, GroupsRepository $groupsRepository): Response
    {
        if($specificationRepository->findByDevice($device)){
            $spec=$specificationRepository->findByDevice($device);
        }
        else{
            $spec=null;
        }
        $comments=$commentRepository->findByDevice($device);
        if ($device->getUser()!=null){
            $worker=$workerRepository->findBy(['id'=>$device->getUser()]);
            $group=$groupsRepository->findByWorker($worker[0]);
            if($spec!=null){
                return $this->render('device/show.html.twig', [
                    'device' => $device,
                    'specification' =>$spec[0],
                    'user' =>$worker[0],
                    'comments'=>$comments,
                    'group' => $group[0],
                ]);
            }else{
                return $this->render('device/show.html.twig', [
                    'device' => $device,
                    'specification' =>null,
                    'user' =>$worker[0],
                    'comments'=>$comments,
                    'group' => $group[0],
                ]);
            }
        }else{
            if($spec!=null){
                return $this->render('device/show.html.twig', [
                    'device' => $device,
                    'specification' =>$spec[0],
                    'comments'=>$comments,
                    'user'=>null,
                    'group' => null,
                ]);
            }else{
                return $this->render('device/show.html.twig', [
                    'device' => $device,
                    'specification' =>null,
                    'comments'=>$comments,
                    'user'=>null,
                    'group' => null,
                ]);
            }
        }
    }

    #[Route('/{id}/edit', name: 'app_device_edit', methods: ['GET', 'POST'])]
    #[IsGranted("ROLE_ADMIN")]
    public function edit(Request $request, Device $device, DeviceRepository $deviceRepository, $id): Response
    {
        $form = $this->createForm(DeviceType::class, $device);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $deviceRepository->save($device, true);
            $this->addFlash(
                'notice',
                'Device has been edited'
            );

            return $this->redirectToRoute('app_device_show', ['id'=>$id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('device/edit.html.twig', [
            'device' => $device,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit_worker', name: 'app_device_edit_worker', methods: ['GET', 'POST'])]
    #[IsGranted("ROLE_ADMIN")]
    public function edit_worker(Request $request, Device $device, DeviceRepository $deviceRepository, $id): Response
    {
        $form = $this->createForm(DeviceWorkerType::class, $device);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if($device->getUser()){
                $device->getSpecification()->setStatus('working');
                $this->addFlash(
                    'notice',
                    'User for this device has been changed'
                );
            }
            else{
                $device->getSpecification()->setStatus('ready');
                $this->addFlash(
                    'notice',
                    'User for this device has been removed'
                );
            }
            $deviceRepository->save($device, true);
            return $this->redirectToRoute('app_device_show', ['id'=>$id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('device/edit_worker.html.twig', [
            'device' => $device,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_device_delete', methods: ['POST'])]
    #[IsGranted("ROLE_ADMIN")]
    public function delete(Request $request, Device $device, DeviceRepository $deviceRepository, SpecificationRepository $specificationRepository, CommentRepository $commentRepository, WorkerRepository $workerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$device->getId(), $request->request->get('_token'))) {
            $comments=$commentRepository->findBy(['device'=>$device]);
            foreach ($comments as $comment){
                $commentRepository->remove($comment,true);
            }
            $spec=$specificationRepository->find($device);
            $specificationRepository->remove($spec,true);
            $deviceRepository->remove($device, true);
            $this->addFlash(
                'notice',
                'Device and related entities has been removed'
            );
        }

        return $this->redirectToRoute('app_device_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/device/_delete_form.html.twig
<form method="post" action="{{ path('app_device_delete', {'id': device.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <div class="col text-center">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ device.id) }}">
        <button class="btn btn-danger">Delete Device</button>
    </div>
</form>

templates/device/_form.html.twig
{{ form_start(form) }}
    <div>
        {{ form_errors(form) }}
    </div>
    <div class="row">
        <div class="col-lg-6 col-sm-12 col-md-12">
            {{ form_row(form.name) }}
        </div>
    </div>
    {{ form_widget(form) }}
    <button class="btn btn-warning">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/device/_form_edit_worker.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-warning">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/device/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Device{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-icon card-header-success">
            <div class="card-icon">
                <i class="material-icons">desktop_windows</i>
            </div>
            <h3 class="card-title">Edit Device</h3>
        </div>
        <div class="card-body">
            {{ include('device/_form.html.twig', {'button_label': 'Update'}) }}
            {{ include('device/_delete_form.html.twig') }}
        </div>
        <div class="col text-center">
            <a class="btn btn-primary" href="{{ path('app_device_show',{'id': device.id}) }}">back to device</a>
        </div>
    </div>
{% endblock %}

templates/device/edit_worker.html.twig
{% extends 'base.html.twig' %}

{% block title %}Set User for Device{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-icon card-header-success">
            <div class="card-icon">
                <i class="material-icons">manage_accounts</i>
            </div>
            <h3 class="card-title">Set User for Device</h3>
        </div>
        <div class="card-body">
            {{ include('device/_form_edit_worker.html.twig', {'button_label': 'Update'}) }}
        </div>
        <div class="col text-center">
            <a class="btn btn-primary" href="{{ path('app_device_show',{'id': device.id}) }}">back to device</a>
        </div>
    </div>
{% endblock %}

templates/device/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Device index{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
                <i class="material-icons">list</i>
            </div>
            <h4 class="card-title">Device List</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="devicelist">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Model</th>
                        <th>Manufacturer</th>
                        <th>Ip_address</th>
                        <th>Location</th>
                        <th>Status</th>
                        <th class="text-center" data-exclude="true">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for device in devices %}
                        <tr>
                            <td>{{ device.name }}</td>
                            <td>{{ device.type }}</td>
                            <td>{{ device.model }}</td>
                            <td>{{ device.manufacturer }}</td>
                            <td>{{ device.ipAddress }}</td>
                            <td>{{ device.location }}</td>
                            <td>
                                {% if device.specification %}
                                {% if device.specification.status =='boxed' %}
                                <i class="material-icons">inventory_2</i>
                            {% elseif device.specification.status =='ready'%}
                                <i class="material-icons">inventory</i>
                            {% elseif device.specification.status =='working'%}
                                <i class="material-icons">face</i>
                            {% elseif device.specification.status =='faulty'%}
                                <i class="material-icons">bug_report</i>
                            {% elseif device.specification.status =='service'%}
                                <i class="material-icons">store</i>
                            {% elseif device.specification.status =='destroy'%}
                                <i class="material-icons">delete_forever</i>
                            {% endif %}
                            {% else %}
                                Not Set
                            {% endif %}
                            </td>
                            <td class="td-actions text-right">
                                <a href="{{ path('app_device_show', {'id': device.id}) }}">
                                    <i class="material-icons">open_in_new</i>
                                </a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="10">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if is_granted('ROLE_ADMIN') %}
                <div class="col text-center">
                    <a class="btn btn-success btn-sm" href="{{ path('app_device_new') }}">Add new Device</a>
                </div>
            {% endif %}

        </div>
    </div>
{% endblock %}
{% block add_script%}
   <script>
       $(document).ready(function () {
           $().ready(function () {
               let deviceTable = $("#devicelist").DataTable({
                   "columnDefs": [
                       {
                           "orderable": false,
                           targets: [7]

                       }
                   ],
                   "order": [[0,  'asc']],
                   "pageLength": 25
               });
           })
       })
   </script>
{% endblock %}

templates/device/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Device{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-icon card-header-success">
            <div class="card-icon">
                <i class="material-icons">desktop_windows</i>
            </div>
            <h3 class="card-title">Create new Device</h3>
        </div>
        <div class="card-body">
            {{ include('device/_form.html.twig') }}
        </div>
        <div class="col text-center">
            <a class="btn btn-primary" href="{{ path('app_device_index') }}">back to list</a>
        </div>
    </div>
{% endblock %}