src/Entity/Worker.php
<?php

namespace App\Entity;

use App\Repository\WorkerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WorkerRepository::class)]
class Worker
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $name = null;

    #[ORM\Column(length: 100)]
    private ?string $surname = null;

    #[ORM\Column(length: 102)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'workers')]
    private ?Groups $ad_group = null;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: Device::class)]
    private ?Device $device;


    public function __construct()
    {
        $this->groups = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    
    public function __toString(): string
    {
        return $this->getName();
    }

    public function getAdGroup(): ?Groups
    {
        return $this->ad_group;
    }

    public function setAdGroup(?Groups $ad_group): self
    {
        $this->ad_group = $ad_group;

        return $this;
    }
    /**
     * @return Device|null
     */
    public function getDevice(): ?Device
    {
        return $this->device;
    }
}

templates/user/_delete_form.html.twig
<form method="post" class="col-2" action="{{ path('app_worker_delete', {'id': worker.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ worker.id) }}">
    <button class="btn btn-danger"><i class="material-icons">delete</i></button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-warning">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Worker{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-icon card-header-success">
            <div class="card-icon">
                <i class="material-icons">people</i>
            </div>
            <h3 class="card-title">Edit User</h3>
        </div>
        <div class="card-body">
            {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}
            {{ include('user/_delete_form.html.twig') }}
        </div>
        <div class="col text-center">
            <a class="btn btn-primary" href="{{ path('app_worker_index') }}">back to list</a>
        </div>
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Worker index{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- Material Kit CSS -->
    <link href="{{ asset("mdp/assets/css/material-dashboard.css?v=2.2.2") }}" rel="stylesheet" />
    <link href="{{ asset('device_styl.css') }}" rel="stylesheet"/>
{% endblock %}
{% block body %}
    <div class="card">
        <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
                <i class="material-icons">list</i>
            </div>
            <h4 class="card-title">Users List</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                {% if is_granted('ROLE_OWNER') %}
                    <table class="table" id="workerlist2">
                        <thead>
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Surname</th>
                            <th>Username</th>
                            <th>Description</th>
                            <th>Ad Group</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for worker in workers %}
                            <tr>
                                <td>{{ worker.id }}</td>
                                <td>{{ worker.name }}</td>
                                <td>{{ worker.surname }}</td>
                                <td>{{ worker.username }}</td>
                                <td>{{ worker.description }}</td>
                                <td>{{ worker.adGroup }}</td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="10">no records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                    </div>
                {% else %}
                <table class="table" id="workerlist">
                    <thead>
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Surname</th>
                        <th>Username</th>
                        <th>Description</th>
                        <th>AD group</th>
                        <th class="text-center" data-exclude="true">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for worker in workers %}
                        <tr>
                            <td>{{ worker.id }}</td>
                            <td>{{ worker.name }}</td>
                            <td>{{ worker.surname }}</td>
                            <td>{{ worker.username }}</td>
                            <td>{{ worker.description }}</td>
                            <td>{{ worker.adGroup }}</td>
                            <td class="td-actions text-right">
                                <div class="row justify-content-center">
                                    <div class="col-2">
                                        <a class="btn btn-warning" href="{{ path('app_worker_edit', {'id': worker.id}) }}">
                                            <i class="material-icons">edit</i>
                                        </a>
                                    </div>
                                    {{ include('user/_delete_form.html.twig') }}
                                </div>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="10">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
                    {% if is_granted('ROLE_EDIT_WORKER') %}
                        <div class="col text-center">
                            <a class="btn btn-success btn-sm" href="{{ path('app_worker_new') }}">Add new User</a>
                        </div>
                    {% endif %}
        </div>
        {% endif %}
    </div>
{% endblock %}
{% block add_script%}
    <script>
        $(document).ready(function () {
            $().ready(function () {
                let workerTable = $("#workerlist").DataTable({
                    "columnDefs": [
                        {
                            "orderable": false,
                            targets: [5,6]
                        }
                    ],
                    "order": [[0,  'asc']],
                    "pageLength": 25
                });
            })
            $().ready(function () {
                let workerTable = $("#workerlist2").DataTable({
                    "columnDefs": [
                        {
                            "orderable": false,
                            targets: [5]
                        }
                    ],
                    "order": [[0,  'asc']],
                    "pageLength": 25
                });
            })
        })
    </script>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Worker{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-icon card-header-success">
            <div class="card-icon">
                <i class="material-icons">people</i>
            </div>
            <h3 class="card-title">Create new User</h3>
        </div>
        <div class="card-body">
            {{ include('user/_form.html.twig') }}
        </div>
        <div class="col text-center">
            <a class="btn btn-primary" href="{{ path('app_worker_index') }}">back to list</a>
        </div>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Worker{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-icon card-header-success">
            <div class="card-icon">
                <i class="material-icons">people</i>
            </div>
            <h3 class="card-title">User {{ worker.name }} {{ worker.surname }}</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ worker.id }}</td>
                    </tr>
                    <tr>
                        <th>Username</th>
                        <td>{{ worker.username }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ worker.description }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>

            {% if is_granted('ROLE_EDIT_WORKER') %}
                <a class="btn btn-warning" href="{{ path('app_worker_edit', {'id': worker.id}) }}">edit</a>

                {{ include('user/_delete_form.html.twig') }}
            {% endif %}
        </div>
        <div class="col text-center">
            <a class="btn btn-primary" href="{{ path('app_worker_index') }}">back to list</a>
        </div>
    </div>
{% endblock %}