src/Entity/Specification.php
<?php

namespace App\Entity;

use App\Repository\SpecificationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SpecificationRepository::class)]
class Specification
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Device $device = null;

    #[ORM\Column(length: 20)]
    private ?string $os_version = null;

    #[ORM\Column(length: 30)]
    private ?string $memory = null;

    #[ORM\Column(length: 50)]
    private ?string $processor = null;

    #[ORM\Column(length: 50)]
    private ?string $motherboard = null;

    #[ORM\Column(length: 60)]
    private ?string $graphics = null;

    #[ORM\Column(length: 40)]
    private ?string $harddisk = null;

    #[ORM\Column(length: 80)]
    private ?string $antivirus = null;

    #[ORM\Column(length: 20)]
    private ?string $serial_number = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_of_purchase = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $warranty_exp = null;

    #[ORM\Column(length: 20)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDevice(): ?Device
    {
        return $this->device;
    }

    public function setDevice(Device $device): self
    {
        $this->device = $device;

        return $this;
    }

    public function getOsVersion(): ?string
    {
        return $this->os_version;
    }

    public function setOsVersion(string $os_version): self
    {
        $this->os_version = $os_version;

        return $this;
    }

    public function getMemory(): ?string
    {
        return $this->memory;
    }

    public function setMemory(string $memory): self
    {
        $this->memory = $memory;

        return $this;
    }

    public function getProcessor(): ?string
    {
        return $this->processor;
    }

    public function setProcessor(string $processor): self
    {
        $this->processor = $processor;

        return $this;
    }

    public function getMotherboard(): ?string
    {
        return $this->motherboard;
    }

    public function setMotherboard(string $motherboard): self
    {
        $this->motherboard = $motherboard;

        return $this;
    }

    public function getGraphics(): ?string
    {
        return $this->graphics;
    }

    public function setGraphics(string $graphics): self
    {
        $this->graphics = $graphics;

        return $this;
    }

    public function getHarddisk(): ?string
    {
        return $this->harddisk;
    }

    public function setHarddisk(string $harddisk): self
    {
        $this->harddisk = $harddisk;

        return $this;
    }

    public function getAntivirus(): ?string
    {
        return $this->antivirus;
    }

    public function setAntivirus(string $antivirus): self
    {
        $this->antivirus = $antivirus;

        return $this;
    }

    public function getSerialNumber(): ?string
    {
        return $this->serial_number;
    }

    public function setSerialNumber(string $serial_number): self
    {
        $this->serial_number = $serial_number;

        return $this;
    }

    public function getDateOfPurchase(): ?\DateTimeInterface
    {
        return $this->date_of_purchase;
    }

    public function setDateOfPurchase(\DateTimeInterface $date_of_purchase): self
    {
        $this->date_of_purchase = $date_of_purchase;

        return $this;
    }

    public function getWarrantyExp(): ?\DateTimeInterface
    {
        return $this->warranty_exp;
    }

    public function setWarrantyExp(\DateTimeInterface $warranty_exp): self
    {
        $this->warranty_exp = $warranty_exp;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/SpecificationType.php
<?php

namespace App\Form;

use App\Entity\Specification;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SpecificationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('os_version')
            ->add('memory')
            ->add('processor')
            ->add('motherboard')
            ->add('graphics')
            ->add('harddisk')
            ->add('antivirus')
            ->add('serial_number')
            ->add('date_of_purchase',DateType::class,[
                'attr'=>['class'=>'datetimepicker form-control col-4'],
                'widget'=>'single_text'])
            ->add('warranty_exp',DateType::class,[
                'attr'=>['class'=>'datetimepicker form-control col-4'],
                'widget'=>'single_text'])
            ->add('status',ChoiceType::class,[
                'choices'=>[
                    'Setting up'=>[
                        'In Box'=>'boxed',
                        'Ready for User'=>'ready',
                    ],
                    'Working'=>[
                        'In Use'=>'working',
                    ],
                    'Error'=>[
                        'Faulty'=>'faulty',
                        'In Service'=>'service',
                    ],
                    'Recycle'=>[
                        'Destroy'=>'destroy',
                    ]
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Specification::class,
        ]);
    }
}

src/Controller/SpecificationController.php
<?php

namespace App\Controller;

use App\Entity\Device;
use App\Entity\Specification;
use App\Form\SpecificationType;
use App\Repository\DeviceRepository;
use App\Repository\SpecificationRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/specification')]
#[IsGranted("ROLE_ADMIN")]
class SpecificationController extends AbstractController
{
    #[Route('/', name: 'app_specification_index', methods: ['GET'])]
    public function index(SpecificationRepository $specificationRepository): Response
    {
        return $this->render('specification/index.html.twig', [
            'specifications' => $specificationRepository->findAll(),
        ]);
    }

    #[Route('/new/{device_id}', name: 'app_specification_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SpecificationRepository $specificationRepository, $device_id, DeviceRepository $deviceRepository): Response
    {
        $specification = new Specification();
        $device = $deviceRepository->find($device_id);
        $specification->setDevice($device);
        $form = $this->createForm(SpecificationType::class, $specification);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $specificationRepository->save($specification, true);
            $this->addFlash(
                'notice',
                'Specification has been created for device'
            );
            return $this->redirectToRoute('app_device_show', ['id'=>$device_id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('specification/new.html.twig', [
            'specification' => $specification,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_specification_show', methods: ['GET'])]
    public function show(Specification $specification): Response
    {
        return $this->render('specification/show.html.twig', [
            'specification' => $specification,
        ]);
    }

    #[Route('/{id}/edit/{device_id}', name: 'app_specification_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Specification $specification, SpecificationRepository $specificationRepository,$device_id): Response
    {
        $form = $this->createForm(SpecificationType::class, $specification);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $specificationRepository->save($specification, true);
            $this->addFlash(
                'notice',
                'Specification has been edited'
            );
            return $this->redirectToRoute('app_device_show', ['id'=>$device_id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('specification/edit.html.twig', [
            'specification' => $specification,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_specification_delete', methods: ['POST'])]
    public function delete(Request $request, Specification $specification, SpecificationRepository $specificationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$specification->getId(), $request->request->get('_token'))) {
            $specificationRepository->remove($specification, true);
            $this->addFlash(
                'notice',
                'Specification has been removed'
            );
        }

        return $this->redirectToRoute('app_specification_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/specification/_delete_form.html.twig
<form method="post" action="{{ path('app_specification_delete', {'id': specification.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ specification.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/specification/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-warning">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

{#{{ form_start(form) }}#}
{#    <div>#}
{#        {{ form_errors(form) }}#}
{#    </div>#}
{#    <div class="row">#}
{#        <div class="col-lg-6 col-sm-12 col-md-12">#}
{#            {{ form_row(form) }}#}
{#        </div>#}
{#    </div>#}
{#    {{ form_widget(form) }}#}
{#    <button class="btn">{{ button_label|default('Save') }}</button>#}
{#{{ form_end(form) }}#}

templates/specification/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Specification{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-icon card-header-success">
            <div class="card-icon">
                <i class="material-icons">developer_board</i>
            </div>
            <h3 class="card-title">Edit Specification for {{ specification.device.name }}</h3>
        </div>
        <div class="card-body">
            {{ include('specification/_form.html.twig', {'button_label': 'Update'}) }}
            {{ include('specification/_delete_form.html.twig') }}
        </div>
        <div class="col text-center">
            <a class="btn btn-primary" href="{{ path('app_device_show',{'id': specification.device.id}) }}">back to device</a>
        </div>
    </div>
{% endblock %}

templates/specification/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Specification index{% endblock %}

{% block body %}
    <h1>Specification index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Os_version</th>
                <th>Memory</th>
                <th>Processor</th>
                <th>Motherboard</th>
                <th>Graphics</th>
                <th>Harddisk</th>
                <th>Antivirus</th>
                <th>Serial_number</th>
                <th>Date_of_purchase</th>
                <th>Warranty_exp</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for specification in specifications %}
            <tr>
                <td>{{ specification.id }}</td>
                <td>{{ specification.osVersion }}</td>
                <td>{{ specification.memory }}</td>
                <td>{{ specification.processor }}</td>
                <td>{{ specification.motherboard }}</td>
                <td>{{ specification.graphics }}</td>
                <td>{{ specification.harddisk }}</td>
                <td>{{ specification.antivirus }}</td>
                <td>{{ specification.serialNumber }}</td>
                <td>{{ specification.dateOfPurchase ? specification.dateOfPurchase|date('Y-m-d') : '' }}</td>
                <td>{{ specification.warrantyExp ? specification.warrantyExp|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_specification_show', {'id': specification.id}) }}">show</a>
                    <a href="{{ path('app_specification_edit', {'id': specification.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_specification_new') }}">Create new</a>
{% endblock %}

templates/specification/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Specification{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-icon card-header-success">
            <div class="card-icon">
                <i class="material-icons">developer_board</i>
            </div>
            <h3 class="card-title">Create new Specification</h3>
        </div>
        <div class="card-body">
            {{ include('specification/_form.html.twig') }}
        </div>
        <div class="col text-center">
            <a class="btn btn-primary" href="{{ path('app_device_index') }}">Skip without Specification</a>
        </div>
    </div>
{% endblock %}

templates/specification/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Specification{% endblock %}

{% block body %}
    <h1>Specification</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ specification.id }}</td>
            </tr>
            <tr>
                <th>Os_version</th>
                <td>{{ specification.osVersion }}</td>
            </tr>
            <tr>
                <th>Memory</th>
                <td>{{ specification.memory }}</td>
            </tr>
            <tr>
                <th>Processor</th>
                <td>{{ specification.processor }}</td>
            </tr>
            <tr>
                <th>Motherboard</th>
                <td>{{ specification.motherboard }}</td>
            </tr>
            <tr>
                <th>Graphics</th>
                <td>{{ specification.graphics }}</td>
            </tr>
            <tr>
                <th>Harddisk</th>
                <td>{{ specification.harddisk }}</td>
            </tr>
            <tr>
                <th>Antivirus</th>
                <td>{{ specification.antivirus }}</td>
            </tr>
            <tr>
                <th>Serial_number</th>
                <td>{{ specification.serialNumber }}</td>
            </tr>
            <tr>
                <th>Date_of_purchase</th>
                <td>{{ specification.dateOfPurchase ? specification.dateOfPurchase|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Warranty_exp</th>
                <td>{{ specification.warrantyExp ? specification.warrantyExp|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_specification_index') }}">back to list</a>

    <a href="{{ path('app_specification_edit', {'id': specification.id}) }}">edit</a>

    {{ include('specification/_delete_form.html.twig') }}
{% endblock %}